config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update, :index] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages
  validates :name, presence: true

  def show_latest_message
    if (latest_message = messages.last).present?
      latest_message.body? ? latest_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません'
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :messages
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_messages = @messages.where('id > ?', params[:id]) }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def get_current_user_groups
    @groups = current_user.groups
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  before_action :get_current_user_groups, only: :index

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save(group_params)
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    @group.name = group_params[:name]
    @group.user_ids = group_params[:user_ids]
    if @group.save
      redirect_to root_path, notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_current_user_groups, only: [:index, :create]
  before_action :get_group

  def index
    @message = Message.new
    @messages = get_messages
  end

  def create
    @message = @group.messages.new(message_params)

    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = get_messages
      flash[:alert] = 'メッセージを入力してください'
      render :index
    end
  end
  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def get_group
    @group = Group.find(params[:group_id])
  end

  def get_messages
    @group.messages.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_posted_time(time)
    time.strftime("%Y/%m/%d(%a) %H:%M:%S")
  end
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2="#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat__group_name chat-group-form__input",placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label(class="chat-group-form__label" for="chat_group_チャットメンバーを追加")
        チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input(class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text' name='keyword')
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #chat_group_users
        - @group.users.each do |user|
          .chat-group-user.clearfix
            %input(name='group[user_ids][]' type='hidden' value="#{user.id}")
            %p.chat-group-user__name
              = user.name
            - if user.id != current_user.id
              %div(class="user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn" data-user-id="#{user.id}" data-user-name="#{user.name}")
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render '/groups/form'

app/views/groups/index.html.haml
.wrapper
  = render partial: '/layouts/side_bar', locals: { groups: @groups }

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render '/groups/form'

app/views/layouts/_flash.html.haml
- flash.each do |key, val|
  = content_tag :div, val, class: "flash flash__#{key}"

app/views/layouts/_side_bar.html.haml
.chat-side
  .side-header
    %p.side-header__user-name
      = current_user.name
    %ul.user-menu
      %li.user-menu__new-group
        = link_to new_group_path, data: {"turbolinks" => false} do
          = fa_icon "edit"
      %li.user-menu__edit-user
        = link_to edit_user_registration_path(current_user) do
          = fa_icon "cog"
  .groups
    - groups.each do |group|
      = link_to group_messages_path(group), data: {"turbolinks" => false} do
        .group
          %p.group__group-name
            = group.name
          %p.group__latest-message
            = group.show_latest_message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
%div(class='message' data-message-id="#{message.id}")
  .upper-info
    %p.upper-info__user
      = message.user.name
    %p.upper-info__date
      = format_posted_time(message.created_at)
  %p.message__text
    = message.body
  = image_tag message.image.url class: 'message__text__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render partial: '/layouts/side_bar', locals: { groups: @groups }

  .chat-main
    .main-header
      %div(class="current-group" data-group-id="1")
        %h2.current-group__name
          = @group.name
        %ul.member-list
          Member：
          - @group.users.each do |user|
            %li.member-list__member
              = user.name
      - if params[:group_id]
        = link_to edit_group_path(params[:group_id]), data: {"turbolinks" => false} do
          .main-header__edit-btn Edit
    .messages
      = render @messages
    .form
      = form_for [@group, @message] do |f|
        .input-box
          = f.text_field :body, class: 'input-box__message', placeholder: 'type a message'
          .form__mask
            = f.label :image, class: 'form__mask__image' do
              = fa_icon 'picture-o', class: 'fa-image icon'
              = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'new_message__submit'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'